name: Continous Itegration

on:
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: ["master", "develop"]

jobs:
  ci_verification:
    runs-on: ubuntu-latest
    
    steps:
      - name: Use node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Test Front-End
        working-directory: ./frontend
        run: |
          npm ci
          npm lint
          npm test

      - name: Test User Service
        working-directory: ./user-service
        run: |
          npm ci
          npm run lint
          npm run test  
          
      - name: Test Project Service
        working-directory: ./project-service
        run: |
          npm ci
          npm run lint
          npm run test  
          
      - name: Test Monitor Service
        working-directory: ./monitor-service
        run: |
          npm ci
          npm run lint
          npm run test  
