name: continous-itegration

on:
  workflow_dispatch:
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: ["master", "develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install the dependencies
        run: npm ci
      - name: Build the application
        run: npm run predeploy

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run the lint checks
        run: npm run lint
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run tests
        run: npm run test
